---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install prerequisite packages
  apt:
    name: "{{ docker_prerequisites }}"
    state: present
    update_cache: yes
  become: yes

- name: Create keyrings directory if not exists
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download Docker GPG key to keyring
  get_url:
    url: "{{ docker_gpg_url }}"
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
    mode: '0644'
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] {{ docker_repo_url }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: yes

- name: Install latest Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: yes
  become: yes

- name: Ensure Docker service is enabled and started
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

