---
galaxy_info:
  author: rrana
  description: "Ansible role to install the latest Docker on Ubuntu 24.04."
  company: rrana.xyz
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - "24.04"

dependencies: []
